version: '3'
services:
  jira:
    image: cptactionhank/atlassian-jira:latest
    volumes:
       - /docker/jira/_data:/var/atlassian/jira
    ports:
       - "8080:8080"
    deploy: 
      replicas: 4
#volumes:
#   jira: 
#     driver: host
#     driver_opts:
#         source: /docker
    # external: true
    #
    #
