apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jira
  name: jira
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jira
    spec:
      containers:
      - image: jira
        name: jira
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/atlassian/jira
          name: jira
      restartPolicy: Always
      volumes:
      - name: jira
        persistentVolumeClaim:
          claimName: jira
status: {}
