version: '3'

services:
  bitbucket:
    image: bitbucket:latest
    volumes:
        - type: volume
          source: bitbucket_vol
          target: /var/atlassian/bitbucket
          volume:
          nocopy: true
     # - /docker/var/atlassian/bitbucket:/var/atlassian/bitbucket
    ports:
      - '80:7990'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.01'
          memory: 512M
        reservations:
         cpus: '0.01'
         memory: 200M

volumes:
  bitbucket_vol:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.0.50,nolock,soft,rw
      device: ":/nfs/shared/shared"
