version: '3'
services:
  bitbucket:
    image: bitbucket:latest
    ports:
     - "81:80"
    deploy:
      replicas: 4
    volumes:
       - /docker/bitbucket/application-data/bitbucke:/var/atlassian/application-data/bitbucke
       - /docker/bitbucket/atlassian/bitbucket:/opt/atlassian/bitbucket
#volumes:
#   bitbucket:
#     external: true     
#   bitbucket_install_dir:
#     external: true

