#/docker/docker/bitbucket:/var/atlassian/application-data/bitbucket -d -p 7990:7990 -p 7999:7999 bitbucket:latest
version: '3'

services:
  bitbucket:
    image: atlassian/bitbucket-server
    volumes:
         - "/docker/docker/shared/shared:/var/atlassian/application-data/bitbucket/shared"
    ports:
      - '80:7990'
      - '81:7991'
    deploy:
      replicas: 2
      resources: 
         limits: 
            cpus: '0.1'
            memory: '512M'
