version: '3'
services:
  bitbucket:
    image: bitbucket:latest
    ports:
     - "81:80"
    deploy:
      replicas: 4
    volumes:
       - bitbucket:/var/atlassian/application-data/bitbucke
       - bitbucket_install_dir:/opt/atlassian/bitbucket
volumes:
   bitbucket:
     external: true     
   bitbucket_install_dir:
     external: true

