version: '3'

services:
  jfrog: 
    image: jfrog:1
    volumes:
      -  /docker/docker/jfrog/artifactory:/var/opt/jfrog/artifactory
    ports:
      - '8081:8081'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.01'
          memory: 512M
        reservations:
         cpus: '0.01'
         memory: 200M

