version: '3'
services:
  mysql:
      build: ./mysql/.
      ports:
       - "3307:3306"
      volumes:
       - mysql:/var/lib/mysql
  web:
    build: ./apache/.
    ports:
     - "80:80"
    volumes:
     - apache:/var/www/html

volumes: 
   apache:
   mysql:
